import type {
  AeFields,
  ArFields,
  CotFields,
  CsFields,
  DocumentFields,
  EcFields,
  EsFields,
  FacFields,
  GanttFields,
  GrFields,
  HtFields,
  OcFields,
  OtFields,
  PlFields,
  PvFields,
  RdFields,
  RecFields,
  RegFields,
  RmFields,
  SowFields,
  TemplateId,
  VtFields,
} from "@kanan/shared";
import type { ComponentType } from "react";

export type ProjectPhase =
  | "pre-venta"
  | "contratacion"
  | "planificacion"
  | "obra"
  | "cierre"
  | "cobro"
  | "admin";

export interface PhaseInfo {
  id: ProjectPhase;
  label: string;
  description: string;
}

export const PHASES: PhaseInfo[] = [
  {
    id: "pre-venta",
    label: "Pre-venta",
    description: "Visita, propuesta y precio",
  },
  {
    id: "contratacion",
    label: "Contratación",
    description: "Alcance y firma de contrato",
  },
  {
    id: "planificacion",
    label: "Planificación",
    description: "Cronograma y asignación de tareas",
  },
  {
    id: "obra",
    label: "En obra",
    description: "Ejecución, materiales y control",
  },
  {
    id: "cierre",
    label: "Cierre",
    description: "Entrega, garantía y satisfacción",
  },
  {
    id: "cobro",
    label: "Cobro",
    description: "Facturas, recibos y estado de cuenta",
  },
  { id: "admin", label: "Admin", description: "Documentos internos" },
];

export interface TemplateRegistryEntry {
  id: TemplateId;
  label: string;
  docType: string;
  prefix: string;
  component: ComponentType;
  defaultFields: () => DocumentFields;
  hasLineItems: boolean;
  hasTotals: boolean;
  isInternal: boolean;
  phase: ProjectPhase;
}

// ── Helpers ────────────────────────────────────────────────────────────────
function today() {
  const d = new Date();
  const months = [
    "ENE",
    "FEB",
    "MAR",
    "ABR",
    "MAY",
    "JUN",
    "JUL",
    "AGO",
    "SEP",
    "OCT",
    "NOV",
    "DIC",
  ];
  return `${d.getDate()} · ${months[d.getMonth()]} · ${d.getFullYear()}`;
}

function emptyItem() {
  return { description: "", unit: "", qty: 1, unitPrice: 0, total: 0 };
}

const DEFAULT_GANTT_PHASES = [
  { name: "01 · Demolición", startWeek: 1, endWeek: 1, color: "#B95D34" },
  { name: "02 · Estructura", startWeek: 1, endWeek: 2, color: "#B95D34" },
  { name: "03 · Albañilería", startWeek: 2, endWeek: 3, color: "#6B7A3F" },
  { name: "04 · Instalaciones", startWeek: 3, endWeek: 4, color: "#6B7A3F" },
  { name: "05 · Enchapes", startWeek: 4, endWeek: 5, color: "#1F1D1B" },
  { name: "06 · Carpintería", startWeek: 5, endWeek: 6, color: "#B95D34" },
  { name: "07 · Pintura", startWeek: 6, endWeek: 7, color: "#6B7A3F" },
  { name: "08 · Limpieza", startWeek: 8, endWeek: 8, color: "#1F1D1B" },
];

// ── Lazy imports (avoids circular deps at module init) ────────────────────
const lazy = (path: string) => {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return (() => null) as any; // replaced at runtime by direct import in registry below
};

// ── Default fields factories ───────────────────────────────────────────────
const defaults: Record<TemplateId, () => DocumentFields> = {
  cot: (): CotFields => ({
    docNumber: "COT-2026-0001",
    date: today(),
    validUntil: "",
    clientName: "",
    clientPhone: "",
    clientEmail: "",
    projectName: "",
    address1: "",
    address2: "",
    vtRef: "",
    items: [emptyItem()],
    subtotal: 0,
    itbis: 0,
    total: 0,
    conditions:
      "50% al inicio · 25% al completar estructura · 25% a la entrega.",
  }),
  fac: (): FacFields => ({
    docNumber: "FAC-2026-0001",
    date: today(),
    ncf: "B01 00000001",
    rnc: "",
    ncfType: "Crédito Fiscal",
    clientName: "",
    clientCedula: "",
    clientPhone: "",
    projectName: "",
    cotRef: "",
    items: [emptyItem()],
    subtotal: 0,
    itbis: 0,
    total: 0,
    paymentMethod: "Transferencia bancaria",
    dueDate: "",
    bankName: "Banco Popular",
    bankAccount: "000-000000-0",
  }),
  rec: (): RecFields => ({
    docNumber: "REC-2026-0001",
    date: today(),
    clientName: "",
    amount: 0,
    amountWords: "",
    concept: "",
    facRef: "",
    reference: "",
    paymentMethod: "Transferencia",
    bankConfirmation: "",
    balanceNote: "",
  }),
  sow: (): SowFields => ({
    docNumber: "SOW-2026-0001",
    date: today(),
    clientName: "",
    clientCedula: "",
    clientPhone: "",
    projectName: "",
    address1: "",
    address2: "",
    cotRef: "",
    startDate: "",
    endDate: "",
    scopeIncluded: ["", ""],
    scopeExcluded: [""],
    tranches: [
      { label: "Tramo 1 · Inicio", percentage: 50, amount: 0 },
      { label: "Tramo 2 · Estructura", percentage: 25, amount: 0 },
      { label: "Tramo 3 · Entrega", percentage: 25, amount: 0 },
    ],
    warrantyText:
      "12 meses sobre trabajos estructurales · 6 meses sobre acabados.",
  }),
  ot: (): OtFields => ({
    docNumber: "OT-2026-0001",
    date: today(),
    clientName: "",
    clientCedula: "",
    projectName: "",
    address1: "",
    address2: "",
    technician: "",
    supervisor: "",
    startDate: "",
    estimatedDelivery: "",
    sowRef: "",
    status: "en-curso",
    tasks: [
      { description: "", responsible: "", days: "", status: "pendiente" },
    ],
    materials: "",
    observations: "",
  }),
  gantt: (): GanttFields => ({
    docNumber: "GANTT-2026-0001",
    period: "",
    projectName: "",
    clientName: "",
    sowRef: "",
    phases: DEFAULT_GANTT_PHASES,
  }),
  reg: (): RegFields => ({
    docNumber: "REG-2026-0001",
    updatedDate: today(),
    rows: [
      {
        ref: "",
        client: "",
        project: "",
        status: "activo",
        startDate: "",
        endDate: "",
        amount: 0,
      },
    ],
  }),
  oc: (): OcFields => ({
    docNumber: "OC-2026-0001",
    date: today(),
    clientName: "",
    projectName: "",
    sowRef: "",
    requestedBy: "",
    changeDescription: "",
    justification: "",
    items: [emptyItem()],
    subtotal: 0,
    itbis: 0,
    total: 0,
    originalContractAmount: 0,
    additionalDays: "",
    newDeliveryDate: "",
    terms: "",
  }),
  ae: (): AeFields => ({
    docNumber: "AE-2026-0001",
    date: today(),
    clientName: "",
    clientCedula: "",
    projectName: "",
    address1: "",
    address2: "",
    sowRef: "",
    startDate: "",
    deliveryDate: "",
    executedWorks: [""],
    deliverables: [""],
    totalContract: 0,
    paid: 0,
    balance: 0,
    warrantyText: "12 meses sobre trabajos estructurales.",
    clientObservations: "",
  }),
  pl: (): PlFields => ({
    docNumber: "PL-2026-0001",
    walkthroughDate: today(),
    clientName: "",
    projectName: "",
    sowRef: "",
    walkthroughBy: "",
    targetCloseDate: "",
    items: [
      {
        number: 1,
        location: "",
        description: "",
        responsible: "",
        date: "",
        status: "pendiente",
      },
    ],
    observations: "",
  }),
  rd: (): RdFields => ({
    docNumber: "RD-2026-0001",
    date: today(),
    projectName: "",
    otRef: "",
    dayOf: "Día 1",
    supervisor: "",
    weather: "Soleado",
    personnel: [{ name: "", role: "", entry: "8:00", exit: "5:00", hours: 8 }],
    worksDone: [""],
    materialsReceived: [""],
    incidents: "Sin incidencias.",
    progressPercent: "",
    daysElapsed: "",
    scheduleStatus: "en-curso",
    planTomorrow: "",
  }),
  vt: (): VtFields => ({
    docNumber: "VT-2026-0001",
    date: today(),
    clientName: "",
    clientPhone: "",
    clientEmail: "",
    clientCedula: "",
    address1: "",
    address2: "",
    propertyType: "Apartamento",
    area: "",
    constructionYear: "",
    clientType: "Residente",
    areasToIntervene: [
      { label: "Sala", checked: false },
      { label: "Cocina", checked: false },
      { label: "Baño principal", checked: false },
      { label: "Habitación principal", checked: false },
      { label: "Balcón / Terraza", checked: false },
      { label: "Área de servicio", checked: false },
    ],
    currentCondition: "",
    requestedWorks: [""],
    measurements: [{ space: "", length: "", width: "", height: "", area: 0 }],
    clientReferences: "",
    logisticsRestrictions: "",
    estimatedRange: "",
    estimatedDuration: "",
    possibleStart: "",
    nextSteps: "",
  }),
  cs: (): CsFields => ({
    docNumber: "CS-2026-0001",
    date: today(),
    projectName: "",
    projectAddress: "",
    sowRef: "",
    contractorName: "KANAN Remodelaciones",
    contractorId: "",
    contractorAddress: "Santo Domingo, RD",
    contracteeName: "",
    contracteeRep: "",
    contracteeId: "",
    contracteeRnc: "",
    contracteeAddress: "",
    clauses: [
      { title: "PRIMERA · Objeto del contrato", body: "" },
      { title: "SEGUNDA · Alcance", body: "" },
      { title: "TERCERA · Plazo de ejecución", body: "" },
      { title: "CUARTA · Precio y forma de pago", body: "" },
      { title: "QUINTA · Obligaciones del contratista", body: "" },
      { title: "SEXTA · Obligaciones del contratante", body: "" },
      { title: "SÉPTIMA · Modificaciones", body: "" },
      { title: "OCTAVA · Garantía", body: "" },
      { title: "NOVENA · Fuerza mayor", body: "" },
      { title: "DÉCIMA · Resolución de conflictos", body: "" },
      { title: "UNDÉCIMA · Vigencia", body: "" },
    ],
    closingText:
      "En fe de lo cual, las partes firman el presente contrato en dos (2) ejemplares de igual tenor y valor.",
  }),
  pv: (): PvFields => ({
    docNumber: "PV-2026-0001",
    date: today(),
    clientName: "",
    clientLocation: "",
    projectName: "",
    projectSize: "",
    tagline: "",
    subtitle: "",
    executiveSummary: "",
    pullQuote: "",
    approaches: [
      { code: "A", title: "", body: "" },
      { code: "B", title: "", body: "" },
    ],
    phases: [
      { number: "01", phase: "", keyWorks: "", weeks: "", investment: 0 },
    ],
    totalInvestment: 0,
    whyKanan: [
      { number: "01", title: "", body: "" },
      { number: "02", title: "", body: "" },
      { number: "03", title: "", body: "" },
      { number: "04", title: "", body: "" },
    ],
    ctaTagline: "",
    ctaBody: "",
    validity: "30 días",
    reserveCondition: "Pago inicial 50%",
    contactPhone: "+1 809 000 0000",
  }),
  gr: (): GrFields => ({
    docNumber: "GR-2026-0001",
    date: today(),
    clientName: "",
    clientCedula: "",
    projectName: "",
    address1: "",
    address2: "",
    sowRef: "",
    aeRef: "",
    warrantyStart: "",
    warrantyEnd: "",
    coveragePeriodText: "",
    worksCovered: [""],
    exclusions: [""],
    claimProcess: "",
    signatoryName: "KANAN Remodelaciones",
    rnc: "",
  }),
  ec: (): EcFields => ({
    docNumber: "EC-2026-0001",
    cutDate: today(),
    clientName: "",
    clientCedula: "",
    projectName: "",
    sowRef: "",
    totalContracted: 0,
    totalPaid: 0,
    balance: 0,
    nextDueDate: "",
    movements: [
      {
        date: "",
        concept: "",
        document: "",
        charge: null,
        credit: null,
        balance: 0,
      },
    ],
    nextCharge: { concept: "", amount: 0, dueDate: "" },
    paymentNote: "",
  }),
  es: (): EsFields => ({
    docNumber: "ES-2026-0001",
    date: today(),
    clientName: "",
    clientCedula: "",
    projectAndDate: "",
    ratings: [
      { aspect: "Comunicación y respuesta", score: 5 },
      { aspect: "Calidad del trabajo", score: 5 },
      { aspect: "Cumplimiento de plazos", score: 5 },
      { aspect: "Limpieza y orden", score: 5 },
      { aspect: "Relación calidad / precio", score: 5 },
    ],
    bestThings: "",
    improvements: "",
    wouldRecommend: "yes",
    testimonialConsent: "named",
    testimonial: "",
  }),
  ht: (): HtFields => ({
    docNumber: "HT-2026-0001",
    date: today(),
    weekRange: "",
    projectName: "",
    supervisor: "",
    period: "",
    paymentStatus: "pendiente",
    rows: [
      {
        name: "",
        role: "",
        days: [null, null, null, null, null, null],
        totalDays: 0,
        dailyRate: 0,
        total: 0,
      },
    ],
    totalDaysPerson: 0,
    totalPayroll: 0,
    observations: "",
    paymentMethod: "Transferencia",
    paymentDate: "",
    paymentTime: "",
  }),
  rm: (): RmFields => ({
    docNumber: "RM-2026-0001",
    date: today(),
    supplierName: "",
    supplierAddress: "",
    supplierContact: "",
    requestedBy: "",
    authorizedBy: "",
    otRef: "",
    projectName: "",
    urgency: "Normal",
    deliveryMethod: "Entrega en obra",
    paymentTerms: "Crédito 30 días",
    items: [
      {
        number: 1,
        description: "",
        spec: "",
        unit: "",
        qty: 1,
        refPrice: 0,
        subtotal: 0,
      },
    ],
    subtotal: 0,
    itbis: 0,
    total: 0,
    dispatchInstructions: "",
    authorizedBudget: 0,
    thisRequisition: 0,
    remainingMargin: 0,
  }),
  ar: (): ArFields => ({
    docNumber: "AR-2026-0001",
    dateTime: today(),
    projectName: "",
    clientName: "",
    location: "",
    duration: "",
    attendees: [{ name: "", role: "", status: "Presente" }],
    agenda: [""],
    decisions: [{ description: "", justification: "" }],
    actionItems: [
      { task: "", responsible: "", deadline: "", status: "pendiente" },
    ],
    nextMeeting: { date: "", modality: "", topic: "" },
  }),
};

// ── Registry ────────────────────────────────────────────────────────────────
// Components are imported dynamically in the resolver to avoid circular deps.
// The registry stores only metadata + defaultFields factories here.

export const TEMPLATE_META: Record<
  TemplateId,
  Omit<TemplateRegistryEntry, "component">
> = {
  // Pre-venta
  vt: {
    id: "vt",
    label: "VT",
    docType: "Visita Técnica",
    prefix: "VT",
    defaultFields: defaults.vt,
    hasLineItems: false,
    hasTotals: false,
    isInternal: false,
    phase: "pre-venta",
  },
  pv: {
    id: "pv",
    label: "PV",
    docType: "Propuesta Visual",
    prefix: "PV",
    defaultFields: defaults.pv,
    hasLineItems: false,
    hasTotals: false,
    isInternal: false,
    phase: "pre-venta",
  },
  cot: {
    id: "cot",
    label: "COT",
    docType: "Cotización",
    prefix: "COT",
    defaultFields: defaults.cot,
    hasLineItems: true,
    hasTotals: true,
    isInternal: false,
    phase: "pre-venta",
  },
  // Contratación
  sow: {
    id: "sow",
    label: "SOW",
    docType: "Alcance de Trabajo",
    prefix: "SOW",
    defaultFields: defaults.sow,
    hasLineItems: false,
    hasTotals: false,
    isInternal: false,
    phase: "contratacion",
  },
  cs: {
    id: "cs",
    label: "CS",
    docType: "Contrato de Servicios",
    prefix: "CS",
    defaultFields: defaults.cs,
    hasLineItems: false,
    hasTotals: false,
    isInternal: false,
    phase: "contratacion",
  },
  // Planificación
  gantt: {
    id: "gantt",
    label: "GANTT",
    docType: "Cronograma de Obra",
    prefix: "GANTT",
    defaultFields: defaults.gantt,
    hasLineItems: false,
    hasTotals: false,
    isInternal: true,
    phase: "planificacion",
  },
  ot: {
    id: "ot",
    label: "OT",
    docType: "Orden de Trabajo",
    prefix: "OT",
    defaultFields: defaults.ot,
    hasLineItems: false,
    hasTotals: false,
    isInternal: true,
    phase: "planificacion",
  },
  // En obra
  rd: {
    id: "rd",
    label: "RD",
    docType: "Reporte Diario",
    prefix: "RD",
    defaultFields: defaults.rd,
    hasLineItems: false,
    hasTotals: false,
    isInternal: true,
    phase: "obra",
  },
  rm: {
    id: "rm",
    label: "RM",
    docType: "Requisición de Materiales",
    prefix: "RM",
    defaultFields: defaults.rm,
    hasLineItems: true,
    hasTotals: true,
    isInternal: true,
    phase: "obra",
  },
  ht: {
    id: "ht",
    label: "HT",
    docType: "Hoja de Tiempo",
    prefix: "HT",
    defaultFields: defaults.ht,
    hasLineItems: false,
    hasTotals: false,
    isInternal: true,
    phase: "obra",
  },
  ar: {
    id: "ar",
    label: "AR",
    docType: "Acta de Reunión",
    prefix: "AR",
    defaultFields: defaults.ar,
    hasLineItems: false,
    hasTotals: false,
    isInternal: false,
    phase: "obra",
  },
  oc: {
    id: "oc",
    label: "OC",
    docType: "Orden de Cambio",
    prefix: "OC",
    defaultFields: defaults.oc,
    hasLineItems: true,
    hasTotals: true,
    isInternal: false,
    phase: "obra",
  },
  pl: {
    id: "pl",
    label: "PL",
    docType: "Punch List",
    prefix: "PL",
    defaultFields: defaults.pl,
    hasLineItems: false,
    hasTotals: false,
    isInternal: true,
    phase: "obra",
  },
  // Cierre
  ae: {
    id: "ae",
    label: "AE",
    docType: "Acta de Entrega",
    prefix: "AE",
    defaultFields: defaults.ae,
    hasLineItems: false,
    hasTotals: false,
    isInternal: false,
    phase: "cierre",
  },
  gr: {
    id: "gr",
    label: "GR",
    docType: "Carta de Garantía",
    prefix: "GR",
    defaultFields: defaults.gr,
    hasLineItems: false,
    hasTotals: false,
    isInternal: false,
    phase: "cierre",
  },
  es: {
    id: "es",
    label: "ES",
    docType: "Encuesta de Satisfacción",
    prefix: "ES",
    defaultFields: defaults.es,
    hasLineItems: false,
    hasTotals: false,
    isInternal: false,
    phase: "cierre",
  },
  // Cobro
  fac: {
    id: "fac",
    label: "FAC",
    docType: "Factura",
    prefix: "FAC",
    defaultFields: defaults.fac,
    hasLineItems: true,
    hasTotals: true,
    isInternal: false,
    phase: "cobro",
  },
  rec: {
    id: "rec",
    label: "REC",
    docType: "Recibo de Pago",
    prefix: "REC",
    defaultFields: defaults.rec,
    hasLineItems: false,
    hasTotals: false,
    isInternal: false,
    phase: "cobro",
  },
  ec: {
    id: "ec",
    label: "EC",
    docType: "Estado de Cuenta",
    prefix: "EC",
    defaultFields: defaults.ec,
    hasLineItems: false,
    hasTotals: false,
    isInternal: false,
    phase: "cobro",
  },
  // Admin
  reg: {
    id: "reg",
    label: "REG",
    docType: "Registro de Proyectos",
    prefix: "REG",
    defaultFields: defaults.reg,
    hasLineItems: false,
    hasTotals: false,
    isInternal: true,
    phase: "admin",
  },
};

export const TEMPLATE_ORDER: TemplateId[] = [
  "cot",
  "fac",
  "rec",
  "sow",
  "ot",
  "gantt",
  "reg",
  "oc",
  "ae",
  "pl",
  "rd",
  "vt",
  "cs",
  "pv",
  "gr",
  "ec",
  "es",
  "ht",
  "rm",
  "ar",
];

export function getTemplateMeta(id: TemplateId) {
  return TEMPLATE_META[id];
}
